VERILOG = ../src/top/jupiter_ace_ulx4m.v \
    ../src/sys/clk_25_system.v ../src/sys/ps2.v ../src/sys/hdmi.v \
    ../src/fpga_ace.v ../src/jace_logic.v ../src/memory.v ../src/keyboard_for_ace.v \
    ../src/cpu/tv80n.v ../src/cpu/tv80_core.v ../src/cpu/tv80_alu.v \
    ../src/cpu/tv80_reg.v ../src/cpu/tv80_mcode.v
TOP = jupiter_ace

include ulx4m.mk

