VERILOG = ../src/top/jupiter_ace_ulx3s.v \
    ../src/sys/clk_25_system.v ../src/sys/ps2_port.v ../src/sys/hdmi.v \
    ../src/fpga_ace.v ../src/jace_logic.v ../src/memory.v ../src/keyboard_for_ace.v \
    ../src/cpu/tv80n.v ../src/cpu/tv80_core.v ../src/cpu/tv80_alu.v \
    ../src/cpu/tv80_reg.v ../src/cpu/tv80_mcode.v

PIN_DEF = ulx3s_ace.lpf

include ulx3s.mk

